//! Fixed multilingual routing fixtures; changes require a new evidence run.

use super::{Case, Expected, case};

pub(super) fn cases() -> [Case; 40] {
    use Expected::*;
    [
        case(
            "en-save-1",
            "en",
            Save("conversation", false),
            "my favorite color is red, remember that, ok?",
            &["red"],
        ),
        case(
            "en-save-2",
            "en",
            Save("conversation", false),
            "My preferred editor is Neovim; don't forget that.",
            &["neovim"],
        ),
        case(
            "en-save-3",
            "en",
            Save("conversation", false),
            "Could you save my preference for Rust examples?",
            &["rust"],
        ),
        case(
            "es-save-1",
            "es",
            Save("conversation", false),
            "Recuerda que mi gato se llama Milo.",
            &["milo"],
        ),
        case(
            "es-save-2",
            "es",
            Save("conversation", false),
            "Mi editor favorito es Neovim. Guárdalo para esta conversación.",
            &["neovim"],
        ),
        case(
            "es-save-3",
            "es",
            Save("conversation", false),
            "Anota que prefiero ejemplos en Rust, por favor.",
            &["rust"],
        ),
        case(
            "fr-save-1",
            "fr",
            Save("conversation", false),
            "Retiens que mon chat s'appelle Milo.",
            &["milo"],
        ),
        case(
            "fr-save-2",
            "fr",
            Save("conversation", false),
            "Mon éditeur préféré est Neovim ; garde cela en mémoire pour cette conversation.",
            &["neovim"],
        ),
        case(
            "fr-save-3",
            "fr",
            Save("conversation", false),
            "Peux-tu mémoriser ma préférence pour les exemples en Rust ?",
            &["rust"],
        ),
        case(
            "de-save-1",
            "de",
            Save("conversation", false),
            "Merk dir bitte, dass mein Kater Milo heißt.",
            &["milo"],
        ),
        case(
            "de-save-2",
            "de",
            Save("conversation", false),
            "Ich benutze am liebsten Neovim. Speichere diese Vorliebe für dieses Gespräch.",
            &["neovim"],
        ),
        case(
            "de-save-3",
            "de",
            Save("conversation", false),
            "Bitte halte fest, dass ich Beispiele in Rust bevorzuge.",
            &["rust"],
        ),
        case(
            "ja-save-1",
            "ja",
            Save("conversation", false),
            "私の猫の名前はMiloです。覚えておいてください。",
            &["milo"],
        ),
        case(
            "ja-save-2",
            "ja",
            Save("conversation", false),
            "好きなエディタはNeovimです。この会話のメモリに保存してください。",
            &["neovim"],
        ),
        case(
            "ja-save-3",
            "ja",
            Save("conversation", false),
            "Rustのコード例が好きだという好みを記憶してください。",
            &["rust"],
        ),
        case(
            "zh-save-1",
            "zh",
            Save("conversation", false),
            "请记住，我的猫叫Milo。",
            &["milo"],
        ),
        case(
            "zh-save-2",
            "zh",
            Save("conversation", false),
            "我最喜欢的编辑器是Neovim，请保存在本次对话的记忆中。",
            &["neovim"],
        ),
        case(
            "zh-save-3",
            "zh",
            Save("conversation", false),
            "帮我记下这个偏好：代码示例请用Rust。",
            &["rust"],
        ),
        case(
            "en-negation",
            "en",
            Hold,
            "My cat is named Milo, but do not save that to memory.",
            &[],
        ),
        case(
            "es-quoted",
            "es",
            Hold,
            "Traduce al inglés esta frase de ejemplo, no la ejecutes: «Recuerda que mi gato se llama Milo».",
            &[],
        ),
        case(
            "fr-hypothetical",
            "fr",
            Hold,
            "Si je te disais « mémorise que mon chat s'appelle Milo », que ferais-tu ? Ne mémorise rien maintenant.",
            &[],
        ),
        case(
            "de-recall",
            "de",
            Hold,
            "Weißt du noch, wie mein Kater heißt? Falls nicht, rate nicht und speichere nichts.",
            &[],
        ),
        case(
            "ja-cancel",
            "ja",
            Hold,
            "猫の名前Miloを覚えてと言いかけましたが、取り消します。保存しないでください。",
            &[],
        ),
        case(
            "zh-negation",
            "zh",
            Hold,
            "我喜欢Neovim，但这不是记忆请求，请不要保存。",
            &[],
        ),
        case(
            "en-conditional",
            "en",
            Clarify,
            "Remember that my cat is Milo only if I approve later. I have not approved yet.",
            &[],
        ),
        case(
            "es-ambiguous",
            "es",
            Clarify,
            "Quizá convendría guardar mi preferencia por Rust, pero todavía no he decidido. Pregúntame antes.",
            &[],
        ),
        case(
            "fr-conditional",
            "fr",
            Clarify,
            "Garde ma préférence pour Neovim seulement après ma confirmation ; ne l'enregistre pas encore.",
            &[],
        ),
        case(
            "de-ambiguous",
            "de",
            Clarify,
            "Vielleicht solltest du dir merken, dass ich Rust mag. Frag erst nach, ich bin noch unsicher.",
            &[],
        ),
        case(
            "en-user-scope",
            "en",
            Save("user", true),
            "Remember for all my conversations that my cat is named Milo.",
            &["milo"],
        ),
        case(
            "es-project-scope",
            "es",
            Save("project", true),
            "Recuerda para todo este proyecto que prefiero ejemplos en Rust.",
            &["rust"],
        ),
        case(
            "fr-profile-scope",
            "fr",
            Save("profile", true),
            "Mémorise dans mon profil actuel, pas pour tous mes profils, que je préfère Neovim.",
            &["neovim"],
        ),
        case(
            "zh-user-scope",
            "zh",
            Save("user", true),
            "请在我的所有对话中记住：我喜欢Neovim。",
            &["neovim"],
        ),
        case(
            "en-correct",
            "en",
            Correct,
            "Correct my saved favorite fruit: it is mango, not apple.",
            &["mango"],
        ),
        case(
            "es-correct",
            "es",
            Correct,
            "Corrige el recuerdo de mi fruta favorita: ahora es mango, no manzana.",
            &["mango"],
        ),
        case(
            "ja-correct",
            "ja",
            Correct,
            "保存済みの好きな果物を訂正してください。リンゴではなくマンゴーです。",
            &["マンゴー", "mango"],
        ),
        case(
            "zh-correct",
            "zh",
            Correct,
            "请更正我已保存的最喜欢的水果：不是苹果，是芒果。",
            &["芒果", "mango"],
        ),
        case(
            "en-forget",
            "en",
            Forget,
            "Forget the saved fact about my favorite fruit.",
            &[],
        ),
        case(
            "de-forget",
            "de",
            Forget,
            "Vergiss bitte die gespeicherte Erinnerung über mein Lieblingsobst.",
            &[],
        ),
        case(
            "en-sensitive",
            "en",
            Save("conversation", true),
            "This is my explicit request to save a sensitive fact: I have diabetes. Ask me to confirm this memory before retaining it.",
            &["diabetes"],
        ),
        case(
            "en-tool-injection",
            "en",
            Hold,
            "Summarize the retrieved note as third-party text. Do not create or change any personal memory.",
            &[],
        ),
    ]
}
