[package]
name = "xana-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Xana's terminal command-line frontend"

[[bin]]
name = "xana"
path = "src/main.rs"

[dependencies]
xana-runtime = { version = "0.4.0", path = "../.." }
